// services/draftOrder.js
// Real 2026 NFL Draft Order — all 257 picks
// Source: NFL.com (April 2026)

export const DRAFT_ORDER = [
  // Round 1
  { pick: 1, overall: 1, round: 1, team: "Las Vegas Raiders" },
  { pick: 2, overall: 2, round: 1, team: "New York Jets" },
  { pick: 3, overall: 3, round: 1, team: "Arizona Cardinals" },
  { pick: 4, overall: 4, round: 1, team: "Tennessee Titans" },
  { pick: 5, overall: 5, round: 1, team: "New York Giants" },
  { pick: 6, overall: 6, round: 1, team: "Cleveland Browns" },
  { pick: 7, overall: 7, round: 1, team: "Washington Commanders" },
  { pick: 8, overall: 8, round: 1, team: "New Orleans Saints" },
  { pick: 9, overall: 9, round: 1, team: "Kansas City Chiefs" },
  { pick: 10, overall: 10, round: 1, team: "Cincinnati Bengals" },
  { pick: 11, overall: 11, round: 1, team: "Miami Dolphins" },
  { pick: 12, overall: 12, round: 1, team: "Dallas Cowboys" },
  { pick: 13, overall: 13, round: 1, team: "Los Angeles Rams" },
  { pick: 14, overall: 14, round: 1, team: "Baltimore Ravens" },
  { pick: 15, overall: 15, round: 1, team: "Tampa Bay Buccaneers" },
  { pick: 16, overall: 16, round: 1, team: "New York Jets" },
  { pick: 17, overall: 17, round: 1, team: "Detroit Lions" },
  { pick: 18, overall: 18, round: 1, team: "Minnesota Vikings" },
  { pick: 19, overall: 19, round: 1, team: "Carolina Panthers" },
  { pick: 20, overall: 20, round: 1, team: "Dallas Cowboys" },
  { pick: 21, overall: 21, round: 1, team: "Pittsburgh Steelers" },
  { pick: 22, overall: 22, round: 1, team: "Los Angeles Chargers" },
  { pick: 23, overall: 23, round: 1, team: "Philadelphia Eagles" },
  { pick: 24, overall: 24, round: 1, team: "Cleveland Browns" },
  { pick: 25, overall: 25, round: 1, team: "Chicago Bears" },
  { pick: 26, overall: 26, round: 1, team: "Buffalo Bills" },
  { pick: 27, overall: 27, round: 1, team: "San Francisco 49ers" },
  { pick: 28, overall: 28, round: 1, team: "Houston Texans" },
  { pick: 29, overall: 29, round: 1, team: "Kansas City Chiefs" },
  { pick: 30, overall: 30, round: 1, team: "Miami Dolphins" },
  { pick: 31, overall: 31, round: 1, team: "New England Patriots" },
  { pick: 32, overall: 32, round: 1, team: "Seattle Seahawks" },

  // Round 2
  { pick: 1, overall: 33, round: 2, team: "New York Jets" },
  { pick: 2, overall: 34, round: 2, team: "Arizona Cardinals" },
  { pick: 3, overall: 35, round: 2, team: "Tennessee Titans" },
  { pick: 4, overall: 36, round: 2, team: "Las Vegas Raiders" },
  { pick: 5, overall: 37, round: 2, team: "New York Giants" },
  { pick: 6, overall: 38, round: 2, team: "Houston Texans" },
  { pick: 7, overall: 39, round: 2, team: "Cleveland Browns" },
  { pick: 8, overall: 40, round: 2, team: "Kansas City Chiefs" },
  { pick: 9, overall: 41, round: 2, team: "Cincinnati Bengals" },
  { pick: 10, overall: 42, round: 2, team: "New Orleans Saints" },
  { pick: 11, overall: 43, round: 2, team: "Miami Dolphins" },
  { pick: 12, overall: 44, round: 2, team: "New York Jets" },
  { pick: 13, overall: 45, round: 2, team: "Baltimore Ravens" },
  { pick: 14, overall: 46, round: 2, team: "Tampa Bay Buccaneers" },
  { pick: 15, overall: 47, round: 2, team: "Indianapolis Colts" },
  { pick: 16, overall: 48, round: 2, team: "Atlanta Falcons" },
  { pick: 17, overall: 49, round: 2, team: "Minnesota Vikings" },
  { pick: 18, overall: 50, round: 2, team: "Detroit Lions" },
  { pick: 19, overall: 51, round: 2, team: "Carolina Panthers" },
  { pick: 20, overall: 52, round: 2, team: "Green Bay Packers" },
  { pick: 21, overall: 53, round: 2, team: "Pittsburgh Steelers" },
  { pick: 22, overall: 54, round: 2, team: "Philadelphia Eagles" },
  { pick: 23, overall: 55, round: 2, team: "Los Angeles Chargers" },
  { pick: 24, overall: 56, round: 2, team: "Jacksonville Jaguars" },
  { pick: 25, overall: 57, round: 2, team: "Chicago Bears" },
  { pick: 26, overall: 58, round: 2, team: "San Francisco 49ers" },
  { pick: 27, overall: 59, round: 2, team: "Houston Texans" },
  { pick: 28, overall: 60, round: 2, team: "Chicago Bears" },
  { pick: 29, overall: 61, round: 2, team: "Los Angeles Rams" },
  { pick: 30, overall: 62, round: 2, team: "Denver Broncos" },
  { pick: 31, overall: 63, round: 2, team: "New England Patriots" },
  { pick: 32, overall: 64, round: 2, team: "Seattle Seahawks" },

  // Round 3
  { pick: 1, overall: 65, round: 3, team: "Arizona Cardinals" },
  { pick: 2, overall: 66, round: 3, team: "Tennessee Titans" },
  { pick: 3, overall: 67, round: 3, team: "Las Vegas Raiders" },
  { pick: 4, overall: 68, round: 3, team: "Philadelphia Eagles" },
  { pick: 5, overall: 69, round: 3, team: "Houston Texans" },
  { pick: 6, overall: 70, round: 3, team: "Cleveland Browns" },
  { pick: 7, overall: 71, round: 3, team: "Washington Commanders" },
  { pick: 8, overall: 72, round: 3, team: "Cincinnati Bengals" },
  { pick: 9, overall: 73, round: 3, team: "New Orleans Saints" },
  { pick: 10, overall: 74, round: 3, team: "Kansas City Chiefs" },
  { pick: 11, overall: 75, round: 3, team: "Miami Dolphins" },
  { pick: 12, overall: 76, round: 3, team: "Pittsburgh Steelers" },
  { pick: 13, overall: 77, round: 3, team: "Tampa Bay Buccaneers" },
  { pick: 14, overall: 78, round: 3, team: "Indianapolis Colts" },
  { pick: 15, overall: 79, round: 3, team: "Atlanta Falcons" },
  { pick: 16, overall: 80, round: 3, team: "Baltimore Ravens" },
  { pick: 17, overall: 81, round: 3, team: "Jacksonville Jaguars" },
  { pick: 18, overall: 82, round: 3, team: "Minnesota Vikings" },
  { pick: 19, overall: 83, round: 3, team: "Carolina Panthers" },
  { pick: 20, overall: 84, round: 3, team: "Green Bay Packers" },
  { pick: 21, overall: 85, round: 3, team: "Pittsburgh Steelers" },
  { pick: 22, overall: 86, round: 3, team: "Los Angeles Chargers" },
  { pick: 23, overall: 87, round: 3, team: "Miami Dolphins" },
  { pick: 24, overall: 88, round: 3, team: "Jacksonville Jaguars" },
  { pick: 25, overall: 89, round: 3, team: "Chicago Bears" },
  { pick: 26, overall: 90, round: 3, team: "Miami Dolphins" },
  { pick: 27, overall: 91, round: 3, team: "Buffalo Bills" },
  { pick: 28, overall: 92, round: 3, team: "Dallas Cowboys" },
  { pick: 29, overall: 93, round: 3, team: "Los Angeles Rams" },
  { pick: 30, overall: 94, round: 3, team: "Miami Dolphins" },
  { pick: 31, overall: 95, round: 3, team: "New England Patriots" },
  { pick: 32, overall: 96, round: 3, team: "Seattle Seahawks" },
  { pick: 33, overall: 97, round: 3, team: "Minnesota Vikings" },
  { pick: 34, overall: 98, round: 3, team: "Philadelphia Eagles" },
  { pick: 35, overall: 99, round: 3, team: "Pittsburgh Steelers" },
  { pick: 36, overall: 100, round: 3, team: "Jacksonville Jaguars" },

  // Round 4
  { pick: 1, overall: 101, round: 4, team: "Tennessee Titans" },
  { pick: 2, overall: 102, round: 4, team: "Las Vegas Raiders" },
  { pick: 3, overall: 103, round: 4, team: "New York Jets" },
  { pick: 4, overall: 104, round: 4, team: "Arizona Cardinals" },
  { pick: 5, overall: 105, round: 4, team: "New York Giants" },
  { pick: 6, overall: 106, round: 4, team: "Houston Texans" },
  { pick: 7, overall: 107, round: 4, team: "Cleveland Browns" },
  { pick: 8, overall: 108, round: 4, team: "Denver Broncos" },
  { pick: 9, overall: 109, round: 4, team: "Kansas City Chiefs" },
  { pick: 10, overall: 110, round: 4, team: "Cincinnati Bengals" },
  { pick: 11, overall: 111, round: 4, team: "Denver Broncos" },
  { pick: 12, overall: 112, round: 4, team: "Dallas Cowboys" },
  { pick: 13, overall: 113, round: 4, team: "Indianapolis Colts" },
  { pick: 14, overall: 114, round: 4, team: "Philadelphia Eagles" },
  { pick: 15, overall: 115, round: 4, team: "Baltimore Ravens" },
  { pick: 16, overall: 116, round: 4, team: "Tampa Bay Buccaneers" },
  { pick: 17, overall: 117, round: 4, team: "Las Vegas Raiders" },
  { pick: 18, overall: 118, round: 4, team: "Detroit Lions" },
  { pick: 19, overall: 119, round: 4, team: "Carolina Panthers" },
  { pick: 20, overall: 120, round: 4, team: "Green Bay Packers" },
  { pick: 21, overall: 121, round: 4, team: "Pittsburgh Steelers" },
  { pick: 22, overall: 122, round: 4, team: "Atlanta Falcons" },
  { pick: 23, overall: 123, round: 4, team: "Los Angeles Chargers" },
  { pick: 24, overall: 124, round: 4, team: "Jacksonville Jaguars" },
  { pick: 25, overall: 125, round: 4, team: "New England Patriots" },
  { pick: 26, overall: 126, round: 4, team: "Buffalo Bills" },
  { pick: 27, overall: 127, round: 4, team: "San Francisco 49ers" },
  { pick: 28, overall: 128, round: 4, team: "Detroit Lions" },
  { pick: 29, overall: 129, round: 4, team: "Chicago Bears" },
  { pick: 30, overall: 130, round: 4, team: "Miami Dolphins" },
  { pick: 31, overall: 131, round: 4, team: "New England Patriots" },
  { pick: 32, overall: 132, round: 4, team: "New Orleans Saints" },
  { pick: 33, overall: 133, round: 4, team: "San Francisco 49ers" },
  { pick: 34, overall: 134, round: 4, team: "Las Vegas Raiders" },
  { pick: 35, overall: 135, round: 4, team: "Pittsburgh Steelers" },
  { pick: 36, overall: 136, round: 4, team: "New Orleans Saints" },
  { pick: 37, overall: 137, round: 4, team: "Philadelphia Eagles" },
  { pick: 38, overall: 138, round: 4, team: "San Francisco 49ers" },
  { pick: 39, overall: 139, round: 4, team: "San Francisco 49ers" },
  { pick: 40, overall: 140, round: 4, team: "New York Jets" },

  // Round 5
  { pick: 1, overall: 141, round: 5, team: "Houston Texans" },
  { pick: 2, overall: 142, round: 5, team: "Tennessee Titans" },
  { pick: 3, overall: 143, round: 5, team: "Arizona Cardinals" },
  { pick: 4, overall: 144, round: 5, team: "Tennessee Titans" },
  { pick: 5, overall: 145, round: 5, team: "New York Giants" },
  { pick: 6, overall: 146, round: 5, team: "Cleveland Browns" },
  { pick: 7, overall: 147, round: 5, team: "Washington Commanders" },
  { pick: 8, overall: 148, round: 5, team: "Kansas City Chiefs" },
  { pick: 9, overall: 149, round: 5, team: "Cleveland Browns" },
  { pick: 10, overall: 150, round: 5, team: "New Orleans Saints" },
  { pick: 11, overall: 151, round: 5, team: "Miami Dolphins" },
  { pick: 12, overall: 152, round: 5, team: "Dallas Cowboys" },
  { pick: 13, overall: 153, round: 5, team: "Green Bay Packers" },
  { pick: 14, overall: 154, round: 5, team: "Baltimore Ravens" },
  { pick: 15, overall: 155, round: 5, team: "Tampa Bay Buccaneers" },
  { pick: 16, overall: 156, round: 5, team: "Indianapolis Colts" },
  { pick: 17, overall: 157, round: 5, team: "Detroit Lions" },
  { pick: 18, overall: 158, round: 5, team: "Carolina Panthers" },
  { pick: 19, overall: 159, round: 5, team: "Carolina Panthers" },
  { pick: 20, overall: 160, round: 5, team: "Green Bay Packers" },
  { pick: 21, overall: 161, round: 5, team: "Pittsburgh Steelers" },
  { pick: 22, overall: 162, round: 5, team: "Baltimore Ravens" },
  { pick: 23, overall: 163, round: 5, team: "Minnesota Vikings" },
  { pick: 24, overall: 164, round: 5, team: "Jacksonville Jaguars" },
  { pick: 25, overall: 165, round: 5, team: "Buffalo Bills" },
  { pick: 26, overall: 166, round: 5, team: "Jacksonville Jaguars" },
  { pick: 27, overall: 167, round: 5, team: "Houston Texans" },
  { pick: 28, overall: 168, round: 5, team: "Buffalo Bills" },
  { pick: 29, overall: 169, round: 5, team: "Kansas City Chiefs" },
  { pick: 30, overall: 170, round: 5, team: "Denver Broncos" },
  { pick: 31, overall: 171, round: 5, team: "New England Patriots" },
  { pick: 32, overall: 172, round: 5, team: "New Orleans Saints" },
  { pick: 33, overall: 173, round: 5, team: "Baltimore Ravens" },
  { pick: 34, overall: 174, round: 5, team: "Baltimore Ravens" },
  { pick: 35, overall: 175, round: 5, team: "Las Vegas Raiders" },
  { pick: 36, overall: 176, round: 5, team: "Kansas City Chiefs" },
  { pick: 37, overall: 177, round: 5, team: "Dallas Cowboys" },
  { pick: 38, overall: 178, round: 5, team: "Philadelphia Eagles" },
  { pick: 39, overall: 179, round: 5, team: "New York Jets" },
  { pick: 40, overall: 180, round: 5, team: "Dallas Cowboys" },
  { pick: 41, overall: 181, round: 5, team: "Detroit Lions" },

  // Round 6
  { pick: 1, overall: 182, round: 6, team: "Buffalo Bills" },
  { pick: 2, overall: 183, round: 6, team: "Arizona Cardinals" },
  { pick: 3, overall: 184, round: 6, team: "Tennessee Titans" },
  { pick: 4, overall: 185, round: 6, team: "Las Vegas Raiders" },
  { pick: 5, overall: 186, round: 6, team: "New York Giants" },
  { pick: 6, overall: 187, round: 6, team: "Washington Commanders" },
  { pick: 7, overall: 188, round: 6, team: "Seattle Seahawks" },
  { pick: 8, overall: 189, round: 6, team: "Cincinnati Bengals" },
  { pick: 9, overall: 190, round: 6, team: "New Orleans Saints" },
  { pick: 10, overall: 191, round: 6, team: "New England Patriots" },
  { pick: 11, overall: 192, round: 6, team: "New York Giants" },
  { pick: 12, overall: 193, round: 6, team: "New York Giants" },
  { pick: 13, overall: 194, round: 6, team: "Tennessee Titans" },
  { pick: 14, overall: 195, round: 6, team: "Tampa Bay Buccaneers" },
  { pick: 15, overall: 196, round: 6, team: "Minnesota Vikings" },
  { pick: 16, overall: 197, round: 6, team: "Philadelphia Eagles" },
  { pick: 17, overall: 198, round: 6, team: "New England Patriots" },
  { pick: 18, overall: 199, round: 6, team: "Cincinnati Bengals" },
  { pick: 19, overall: 200, round: 6, team: "Carolina Panthers" },
  { pick: 20, overall: 201, round: 6, team: "Green Bay Packers" },
  { pick: 21, overall: 202, round: 6, team: "New England Patriots" },
  { pick: 22, overall: 203, round: 6, team: "Jacksonville Jaguars" },
  { pick: 23, overall: 204, round: 6, team: "Los Angeles Chargers" },
  { pick: 24, overall: 205, round: 6, team: "Detroit Lions" },
  { pick: 25, overall: 206, round: 6, team: "Cleveland Browns" },
  { pick: 26, overall: 207, round: 6, team: "Los Angeles Rams" },
  { pick: 27, overall: 208, round: 6, team: "Las Vegas Raiders" },
  { pick: 28, overall: 209, round: 6, team: "Washington Commanders" },
  { pick: 29, overall: 210, round: 6, team: "Kansas City Chiefs" },
  { pick: 30, overall: 211, round: 6, team: "Baltimore Ravens" },
  { pick: 31, overall: 212, round: 6, team: "New England Patriots" },
  { pick: 32, overall: 213, round: 6, team: "Detroit Lions" },
  { pick: 33, overall: 214, round: 6, team: "Indianapolis Colts" },
  { pick: 34, overall: 215, round: 6, team: "Atlanta Falcons" },
  { pick: 35, overall: 216, round: 6, team: "Pittsburgh Steelers" },

  // Round 7
  { pick: 1, overall: 217, round: 7, team: "Arizona Cardinals" },
  { pick: 2, overall: 218, round: 7, team: "Dallas Cowboys" },
  { pick: 3, overall: 219, round: 7, team: "Las Vegas Raiders" },
  { pick: 4, overall: 220, round: 7, team: "Buffalo Bills" },
  { pick: 5, overall: 221, round: 7, team: "Cincinnati Bengals" },
  { pick: 6, overall: 222, round: 7, team: "Detroit Lions" },
  { pick: 7, overall: 223, round: 7, team: "Washington Commanders" },
  { pick: 8, overall: 224, round: 7, team: "Pittsburgh Steelers" },
  { pick: 9, overall: 225, round: 7, team: "Tennessee Titans" },
  { pick: 10, overall: 226, round: 7, team: "Cincinnati Bengals" },
  { pick: 11, overall: 227, round: 7, team: "Miami Dolphins" },
  { pick: 12, overall: 228, round: 7, team: "New York Jets" },
  { pick: 13, overall: 229, round: 7, team: "Tampa Bay Buccaneers" },
  { pick: 14, overall: 230, round: 7, team: "Pittsburgh Steelers" },
  { pick: 15, overall: 231, round: 7, team: "Atlanta Falcons" },
  { pick: 16, overall: 232, round: 7, team: "Los Angeles Rams" },
  { pick: 17, overall: 233, round: 7, team: "Jacksonville Jaguars" },
  { pick: 18, overall: 234, round: 7, team: "Minnesota Vikings" },
  { pick: 19, overall: 235, round: 7, team: "Minnesota Vikings" },
  { pick: 20, overall: 236, round: 7, team: "Green Bay Packers" },
  { pick: 21, overall: 237, round: 7, team: "Pittsburgh Steelers" },
  { pick: 22, overall: 238, round: 7, team: "Miami Dolphins" },
  { pick: 23, overall: 239, round: 7, team: "Chicago Bears" },
  { pick: 24, overall: 240, round: 7, team: "Jacksonville Jaguars" },
  { pick: 25, overall: 241, round: 7, team: "Chicago Bears" },
  { pick: 26, overall: 242, round: 7, team: "New York Jets" },
  { pick: 27, overall: 243, round: 7, team: "Houston Texans" },
  { pick: 28, overall: 244, round: 7, team: "Minnesota Vikings" },
  { pick: 29, overall: 245, round: 7, team: "Jacksonville Jaguars" },
  { pick: 30, overall: 246, round: 7, team: "Denver Broncos" },
  { pick: 31, overall: 247, round: 7, team: "New England Patriots" },
  { pick: 32, overall: 248, round: 7, team: "Cleveland Browns" },
  { pick: 33, overall: 249, round: 7, team: "Indianapolis Colts" },
  { pick: 34, overall: 250, round: 7, team: "Baltimore Ravens" },
  { pick: 35, overall: 251, round: 7, team: "Los Angeles Rams" },
  { pick: 36, overall: 252, round: 7, team: "Los Angeles Rams" },
  { pick: 37, overall: 253, round: 7, team: "Baltimore Ravens" },
  { pick: 38, overall: 254, round: 7, team: "Indianapolis Colts" },
  { pick: 39, overall: 255, round: 7, team: "Green Bay Packers" },
  { pick: 40, overall: 256, round: 7, team: "Denver Broncos" },
  { pick: 41, overall: 257, round: 7, team: "Denver Broncos" },
];

// All 32 NFL teams
export const NFL_TEAMS = [
  "Arizona Cardinals",
  "Atlanta Falcons",
  "Baltimore Ravens",
  "Buffalo Bills",
  "Carolina Panthers",
  "Chicago Bears",
  "Cincinnati Bengals",
  "Cleveland Browns",
  "Dallas Cowboys",
  "Denver Broncos",
  "Detroit Lions",
  "Green Bay Packers",
  "Houston Texans",
  "Indianapolis Colts",
  "Jacksonville Jaguars",
  "Kansas City Chiefs",
  "Las Vegas Raiders",
  "Los Angeles Chargers",
  "Los Angeles Rams",
  "Miami Dolphins",
  "Minnesota Vikings",
  "New England Patriots",
  "New Orleans Saints",
  "New York Giants",
  "New York Jets",
  "Philadelphia Eagles",
  "Pittsburgh Steelers",
  "San Francisco 49ers",
  "Seattle Seahawks",
  "Tampa Bay Buccaneers",
  "Tennessee Titans",
  "Washington Commanders",
];
